[
   Var                         -- _1,
   Int                         -- _1,
   Uri                         -- _1,
   Path                        -- _1,
   List                        -- V  [V vs=2 [KW["["] _1] KW["]"]],
   List.1:iter-star            -- _1,
   Assert                      -- KW["assert"] _1 KW[";"] _2,
   With                        -- KW["with"] _1 KW[";"] _2,
   Let                         -- KW["let"] _1 KW["in"] _2,
   Let.1:iter-star             -- _1,
   LetRec                      -- KW["let"] KW["{"] _1 KW["}"],
   LetRec.1:iter-star          -- _1,
   AttributeSet                -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   AttributeSet.1:iter-star    -- _1,
   RecAttributeSet             -- KW["rec"] KW["{"] _1 KW["}"],
   RecAttributeSet.1:iter-star -- _1,
   Bind                        -- _1 KW["="] _2 KW[";"],
   Bind.1:iter-sep             -- _1 KW["."],
   Inherit                     -- V  [V vs=2 [KW["inherit"] _1] KW[";"]],
   Inherit.1:iter              -- _1,
   InheritFrom                 -- KW["inherit"] KW["("] _1 KW[")"] _2 KW[";"],
   InheritFrom.2:iter          -- _1,
   Call                        -- _1 _2,
   Function                    -- _1 KW[":"] _2,
   Function                    -- KW["{"] _1 KW["}"] KW[":"] _2,
   Function.1:iter-sep         -- _1 KW[","],
   Function                    -- _1 KW["@"] KW["{"] _2 KW["}"] KW[":"] _3,
   Function.2:iter-sep         -- _1 KW[","],
   Function                    -- KW["{"] _1 KW["}"] KW["@"] _2 KW[":"] _3,
   Function.1:iter-sep         -- _1 KW[","],
   Arg                         -- _1,
   ArgDefault                  -- _1 KW["?"] _2,
   ArgEllipsis                 -- KW["..."],
   Select                      -- _1 KW["."] _2,
   If                          -- KW["if"] _1 KW["then"] _2 KW["else"] _3,
   Eq                          -- _1 KW["=="] _2,
   NEq                         -- _1 KW["!="] _2,
   Not                         -- KW["!"] _1,
   And                         -- _1 KW["&&"] _2,
   Or                          -- _1 KW["||"] _2,
   Impl                        -- _1 KW["->"] _2,
   Update                      -- _1 KW["//"] _2,
   HasAttr                     -- _1 KW["?"] _2,
   Plus                        -- _1 KW["+"] _2,
   Concat                      -- _1 KW["++"] _2
]